### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by rlarge** [williamjuan027/nativescript-cradleTabBar#3]
I'm getting a uncaught exception when ran on a android device.  Cannot read the property of "items" of undefined

**Comment by rlarge** [comment]
It seems that file:///node_modules\tns-core-modules\ui\tabs\tabs.js is in conflict.  I beleive they updated it and its causing problem.  I'm just learning but ill try to track it down.

**Comment by williamjuan027** [comment]
@rlarge What version of nativescript are you running?

**Comment by rlarge** [comment]
6.4 and sorry it took a bit was on vacation.

**Comment by williamjuan027** [comment]
@rlarge the error you are seeing should be fixed with PR #4 (`master` should work for both android and ios) :)
